apiVersion: apps/v1
kind: Deployment
metadata:
  name: bid-recommendation
  labels:
    app: bid-recommendation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bid-recommendation
  template:
    metadata:
      labels:
        app: bid-recommendation
    spec:
      containers:
      - name: bid-recommendation
        image: bid-recommendation:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 30